steps:
  - label: ":anger: hello"
    command: echo "Hello, World!"
  - label: ":swift: unit tests"
    command: ".buildkite/unit_tests.sh"
    timeout: "2"
    agents:
      xcode_major: '9'
  - label: ":grin: goodbye"
    command: echo "Goodbye cruel world"
  - label: ":whatever: hi"
    command: "say_hi.sh"
